apiVersion: v1
kind: Secret
metadata:
  name: auth-logs
  namespace: omneedia-logging
data:
  users: ${AUTH}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: secure-logs
spec:
  basicAuth:
    secret: auth-logs
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logs-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: omneedia-logging-secure-logs@kubernetescrd
spec:
  rules:
    - host: l.${DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loki-stack
                port:
                  number: 3100
