apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logs-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: l.${DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loki-stack
                port:
                  number: 3100
  tls:
    - secretName: loki-logs-tls
      hosts:
        - l.${DOMAIN}
